### ISSUE TITLE
Cannot print to notebook in "while True:" loop

### ISSUE THREAD

**Issue by valkyriesavage** [adafruit/circuitpython_jupyter_kernel#33]
* CircuitPython Kernel version: 0.3.2
* Python version: 3.9.7
* Operating System: Mac OSX
* Board: (sysname='samd21', nodename='samd21', release='4.1.2', version='4.1.2 on 2019-12-18', machine='Adafruit ItsyBitsy M0 Express with samd21g18')

### Description

I am trying to get outputs from my board in a while True: loop. I can get outputs printed to the notebook outside the loop, but inside the loop I cannot.

### What I Did

Most of this code is copied from an example in the repo, but I did have to change it to use my ItsyBitsy M0's dotstar instead of a neopixel.

```
import time
import board
import adafruit_dotstar

dot = adafruit_dotstar.DotStar(board.APA102_SCK, board.APA102_MOSI, 1, brightness=0.5)

def flash_pixels(flash_speed=0.5):
    print('flashing R')
    dot.fill((255, 0, 0))
    dot.show()
    time.sleep(flash_speed)
    
    print('flashing G')
    dot.fill((0, 255, 0))
    dot.show()
    time.sleep(flash_speed)
    
    print('flashing B')
    dot.fill((0, 0, 255))
    dot.show()
    time.sleep(flash_speed)

flash_pixels() # prints fine
while True:
    flash_pixels() # no prints in terminal or notebook
```

**Comment by ladyada** [comment]
pretty sure the blocks must 'complete' for the output to appear, loops blocks never complete. thats just how jupytr works.
