### ISSUE TITLE
Support for ESP32 ?

### ISSUE THREAD

**Issue by GorgiAstro** [adafruit/circuitpython_jupyter_kernel#35]
Hi folks,

I wanted to give the CircuitPython kernel a try with my ESP32 Feather V2 board, but I see that it's not in the list of supported devices, and none of the ESP32 boards actually, even the newer ESP32-S3 for instance which does have native USB (unlike my ESP32 Feather V2..).

Is there a plan to make the CircuitPython kernel compatible with the ESP32 boards? It would be cool to program them from JupyterLab. 

I tried the examples in https://github.com/adafruit/circuitpython_jupyter_kernel/tree/master/examples , but that didn't work, I get the error `No connection to CiruitPython VM: found no board`. The jupyter log in the terminal shows the correct serial port (`/dev/ttyACM0`) though.

**Comment by brentru** [comment]
The ESP32-S3 should work, as it has Native USB and can access the serial. The README hasn't been updated in a while. 

There are currently no (adafruit) plans to update this library to support the ESP32 (non-native USB workflow) boards with this. However, we are accepting pull requests and would provide testing if someone adds support.

**Comment by GorgiAstro** [comment]
Okay thank you for the information.
